package br.com.gomesar.assembleia.application.commons

enum class ApiErrorCode(val codigo: String) {
    ERRO_NAO_MAPEADO("000"),
    ERRO_REQUESTBODY_NULO("001"),
    ERRO_REQUESTBODY_INVALIDO("002"),
    ERRO_REQUESTPARAM_NULO("004"),
    ERRO_REQUESTPARAM_INVALIDO("005"),
    ERRO_PAUTA_JA_CADASTRADA("006"),
    ERRO_PAUTA_NAO_ENCONTRADA("007"),
    ERRO_SESSAO_CRIAR_PAUTA_NAO_EXISTENTE("008"),
    ERRO_REQUESTBODY_INVALIDFORMAT("009"),
    ERRO_SESSAO_JA_CADASTRADA("010"),
    ERRO_USUARIOSERVICE_NAO_ENCONTRADO("011"),
    ERRO_USUARIOSERVICE_INDISPONIVEL("012"),
    ERRO_VOTO_SESSAO_NAO_CADASTRADA("013"),
    ERRO_VOTO_SESSAO_JA_ENCERRADA("014"),
    ERRO_VOTO_USUARIO_SEM_PERMISSAO("015"),
    ERRO_VOTO_USUARIO_JA_COMPUTADO("016"),
    ERRO_SESSAO_NAO_EXISTENTE("017")
}